feat(refactor): update antd
altence/lightence-admin pull request #267
Opened 2023-03-15 08:55 UTC by saha80

# Description

Migrate to antd v5.

Fixes #249

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Locally.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-03-20 11:34 UTC, leineveber approved these changes

2023-08-29 20:32 UTC, leineveber commented on src/components/Error/Error.styles.ts
> +  font-weight: ${FONT_WEIGHT.semibold};
it would be better to take that from theme object of styled components itself, ${(props => props.theme)}

2023-08-29 20:35 UTC, leineveber commented on src/components/common/BaseBadge/BaseBadge.styles.ts
> +    font-size: ${FONT_SIZE.xs};
same comment, better to take it from styled-components theme but it's not really so important, just FYI

2023-09-10 11:12 UTC, leineveber commented on src/components/common/BaseButton/BaseButton.styles.ts
> +  font-weight: ${FONT_WEIGHT.semibold};
from styled-components theme

2023-09-10 11:12 UTC, leineveber commented on src/components/common/BaseButton/BaseButton.styles.ts
> +        background: rgba(0, 0, 0, 0.018);
hardcoded color? why?

2023-09-10 11:13 UTC, leineveber commented on src/components/common/BaseCalendar/BaseCalendar.styles.ts
> +    font-weight: ${FONT_WEIGHT.bold};
from theme

2023-09-10 11:14 UTC, leineveber commented on src/components/common/BaseCalendar/BaseCalendar.tsx
> +export type BaseCalendarProps = CalendarProps<Dayjs>;
is it necessary to use here explicitly Dayjs? as I remember, from antdv5 Calendar&Pickers come with dayjs by default

2023-09-10 11:14 UTC, leineveber commented on src/components/common/BaseCard/BaseCard.styles.ts
>      font-weight: ${FONT_WEIGHT.bold};
not yours code but refactor pls to theme

2023-09-10 11:15 UTC, leineveber commented on src/components/common/BaseCard/BaseCard.styles.ts
> +      min-height: 48px;
why?

2023-09-10 11:15 UTC, leineveber commented on src/components/common/BaseCard/BaseCard.styles.ts
> +    min-height: 36px;
why?

2023-09-10 11:15 UTC, leineveber commented on src/components/common/BaseCard/BaseCard.styles.ts
>        font-size: ${FONT_SIZE.xxl};
from SC

2023-09-10 11:17 UTC, leineveber commented on src/components/common/BaseCol/BaseCol.styles.ts
> +  font-size: unset;
why?

2023-09-10 11:17 UTC, leineveber commented on src/components/common/BaseFeed/BaseFeed.tsx
> +      style={{ overflow: 'visible' }}
why?

2023-09-10 11:17 UTC, leineveber commented on src/components/common/BaseMenu/BaseMenu.styles.ts
> +    font-size: ${FONT_SIZE.xl};
from SC

2023-09-10 11:17 UTC, leineveber commented on src/components/common/BaseMenu/BaseMenu.styles.ts
> +    font-size: ${FONT_SIZE.xs};
from SC

2023-09-10 11:18 UTC, leineveber commented on src/components/common/BaseModal/BaseModal.tsx
> +  const modalSize = modalSizes[size];
why did you remove info, sucess, warning, error modals?

2023-09-10 11:19 UTC, leineveber commented on src/components/common/BasePagination/BasePagination.styles.ts
> +          color: var(--ant-primary-5);
ant-primary? is it our color?

2023-09-10 11:20 UTC, leineveber commented on src/components/common/BasePagination/BasePagination.styles.ts
> +          color: var(--ant-primary-5);
probably it is our primary color but lighten/darken, we have util function to do this

2023-09-10 11:20 UTC, leineveber commented on src/components/common/BasePagination/BasePagination.styles.ts
> +        border-color: var(--ant-primary-5);
same

2023-09-10 11:21 UTC, leineveber commented on src/components/common/BaseRow/BaseRow.styles.ts
> +  font-size: unset;
why?

2023-09-10 11:21 UTC, leineveber commented on src/components/common/BaseSwitch/BaseSwitch.styles.ts
> +    box-shadow: 0 0 0 2px var(--ant-primary-1);
same

2023-09-10 11:22 UTC, leineveber commented on src/components/common/BaseTable/BaseTable.tsx
> +export const BaseTable = <T extends AnyRecord>(props: BaseTableProps<T>): React.JSX.Element => {
why? isn't it the same as was before?

2023-09-10 11:22 UTC, leineveber commented on src/components/common/BaseTabs/BaseTabs.styles.ts
> +        color: var(--ant-primary-7);
same

2023-09-10 11:23 UTC, leineveber commented on src/components/common/forms/components/BaseButtonsGroup/BaseButtonsGroup.tsx
> +        <BaseButton block ghost onClick={onCancel} {...props}>
isn't ghost a type?

2023-09-10 11:23 UTC, leineveber commented on src/components/common/forms/components/BaseFormItem/BaseFormItem.ts
> +    font-size: ${FONT_SIZE.xs};
from SC

2023-09-10 11:24 UTC, leineveber commented on src/components/common/inputs/MaskedInput/MaskedInput.styles.ts
> +  border-radius: ${BORDER_RADIUS};
from sc

2023-09-10 11:25 UTC, leineveber commented on src/components/common/inputs/SearchInput/SearchInput.styles.ts
> +      font-weight: ${FONT_WEIGHT.semibold};
from sc

2023-09-10 11:27 UTC, leineveber commented on src/components/common/selects/BaseSelect/BaseSelect.styles.ts
> +    font-weight: ${FONT_WEIGHT.medium};
from sc

2023-09-10 11:27 UTC, leineveber commented on src/components/common/selects/BaseSelect/BaseSelect.styles.ts
> +      color: #bfbfbf;
why hardcoded color?

2023-09-10 11:27 UTC, leineveber commented on src/components/common/selects/BaseSelect/BaseSelect.styles.ts
> +      border: 1px solid #f0f0f0;
why hardcoded color?

2023-09-10 11:28 UTC, leineveber commented on src/components/forms/ControlForm/ControlForm.styles.ts
>      font-size: ${FONT_SIZE.md};
refactor pls to sc

2023-09-10 11:29 UTC, leineveber commented on src/components/header/components/GithubButton/GitHubButton.styles.ts
> +  color: ${(props) => BASE_COLORS[props.$isDark ? 'white' : 'black']};
strange construction, can't we use directly from sc theme?

2023-09-10 11:35 UTC, leineveber commented on src/controllers/notificationController.tsx
> +  color: #404040;
hardcoded?

2023-09-10 11:40 UTC, leineveber commented on src/store/middlewares/errorLogging.middleware.ts
> +import { notification } from 'antd';
why?

2023-09-10 11:40 UTC, leineveber commented on src/styles/GlobalStyle.ts
> +      color: var(--ant-primary-5);
same

2023-09-10 11:41 UTC, leineveber commented on src/styles/themeConfig.tsx
> +};
haven't reviewed this but please rereview yourself here

2023-09-10 11:42 UTC, leineveber commented on src/styles/themes/dark/darkTheme.ts
> +  primary1: darkColorsTheme.primary1,
what's the point? we can generate these with util functions

2023-09-10 11:42 UTC, leineveber commented on src/styles/themes/light/lightTheme.ts
> +  primary1: lightColorsTheme.primary1,
same

2023-09-10 11:43 UTC, leineveber commented on src/styles/themes/themeVariables.ts
> +  --ant-primary-1: ${antThemeObject[theme].primary1};
same

2023-09-10 11:43 UTC, leineveber requested changes
some minor comments

2023-09-12 16:17 UTC, saha80 commented on src/components/common/BaseModal/BaseModal.tsx
> +  const modalSize = modalSizes[size];
Those methods were moved to `modalController`, which is used in the `useFeedback` hook.
Static methods of the Modal or Notification don't support the dynamic theme (`<ConfigProvider>`).
https://github.com/ant-design/ant-design/issues/39559
https://ant.design/components/modal

2023-09-12 19:23 UTC, saha80 commented on src/components/common/forms/components/BaseButtonsGroup/BaseButtonsGroup.tsx
> +        <BaseButton block ghost onClick={onCancel} {...props}>
no, it isn't.
https://ant.design/components/button#api

2023-09-12 21:20 UTC, saha80 commented on src/components/common/BaseCalendar/BaseCalendar.tsx
> +export type BaseCalendarProps = CalendarProps<Dayjs>;
`CalendarProps` is defined as a generic type without a default type.
https://github.com/ant-design/ant-design/blob/master/components/calendar/generateCalendar.tsx#L50
https://github.com/ant-design/ant-design/blob/master/components/calendar/index.ts#L6

2023-09-18 17:04 UTC, saha80 commented on src/components/common/selects/BaseSelect/BaseSelect.styles.ts
> +      color: #bfbfbf;
moved to theme object
https://github.com/altence/lightence-ant-design-react-template/blob/refactor/update-antd/src/styles/themes/light/lightTheme.ts#L139

2023-09-18 17:05 UTC, saha80 commented on src/components/common/selects/BaseSelect/BaseSelect.styles.ts
> +      border: 1px solid #f0f0f0;
moved to theme object
https://github.com/altence/lightence-ant-design-react-template/blob/refactor/update-antd/src/styles/themes/light/lightTheme.ts#L140

2023-09-18 17:07 UTC, saha80 commented on src/controllers/notificationController.tsx
> +  color: #404040;
replaced with `theme.textDark`

2023-09-18 17:13 UTC, saha80 commented on src/components/common/BaseButton/BaseButton.styles.ts
> +        background: rgba(0, 0, 0, 0.018);
removed from BaseButton styles, because of BaseButton styles' complexity.

2023-09-18 17:20 UTC, saha80 commented on src/components/common/BaseTable/BaseTable.tsx
> +export const BaseTable = <T extends AnyRecord>(props: BaseTableProps<T>): React.JSX.Element => {
there was a problem during a minor version update.

2023-12-05 09:32 UTC, merged